name: crypto_currency_wallet
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter_bloc: ^6.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0
  decimal: ^0.3.5
  cupertino_icons: ^0.1.3
  charts_common: ^0.9.0
  charts_flutter: ^0.9.0
  injector: ^1.0.8
  json_annotation: ^3.0.1
  google_fonts: ^1.1.0
  crypto_repository:
    path:
      external/crypto_repository
  equatable: ^1.2.3
  shimmer: ^1.1.1


dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.2
  json_serializable: ^3.4.0
  mockito: ^4.1.1
  bloc_test: ^7.0.0
flutter:

  uses-material-design: true
  fonts:
    - family: carolingia
      fonts:
        - asset: fonts/carolingia.ttf
    - family: stonehenge
      fonts:
        - asset: fonts/stonehen.ttf
