name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: 'master'
    - uses: actions/checkout@v1
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
